id: A307130A4
title: Verses of Happiness and Well-Being upon Entering the City of Vaiśālī
type: translation
pechas:
- I4148295B
- I2957659E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:08:00.202499
  last_modified_at: 2023-01-04 12:08:00.202504
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I4148295B/4770: B824
  I2957659E/F777: B824
